#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    n=len(scores)
    best=[]
    worst=[]
    mini=scores[0]
    maxi=scores[0]
    res=[]
    best.append(scores[0])
    worst.append(scores[0])
    for i in range(1,n):
        maxi=max(maxi,scores[i])
        best.append(maxi)
        mini=min(mini,scores[i])
        worst.append(mini)
    res.append(len(list(set(best)))-1)
    res.append(len(list(set(worst)))-1)
    return res
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
